load(
    "//tensorflow/lite/micro:build_def.bzl",
    "micro_copts",
)

package(
    default_visibility = ["//visibility:public"],
    features = ["-layering_check"],
    licenses = ["notice"],
)

cc_library(
    name = "micro_training",
    hdrs = [
        "micro_training.h",
    ],
    copts = micro_copts(),
    deps = [

    ],
)